"""Render docs/coverage/pipeline/README.md from every state's coverage snapshot.

Snapshots (`docs/coverage/pipeline/<STATE>.json`) are written when a run is reviewed for promotion.
The report separates three things the pipeline must never blur: an official source was found, a
structured record was extracted (candidate), and a record is verified in the repository.
"""
from __future__ import annotations
import json
from pathlib import Path

from backend.catalog import ROOT

DIR = ROOT / 'docs/coverage/pipeline'
CATEGORIES = ['tuition_fees', 'cost_of_attendance', 'admissions_tests', 'common_data_set', 'merit_scholarships', 'ap_credit',
              'clep_credit', 'ib_credit', 'dual_enrollment', 'transfer_credit', 'statewide_articulation', 'residency',
              'degree_requirements', 'aid_appeals']
VERIFIED = {'verified_current'}
STRUCTURED = {'verified_current', 'partially_verified_current', 'candidate_ready', 'candidate_exception'}
FOUND = STRUCTURED | {'source_found'}


def pct(n, d):
    return f'{100 * n / d:.0f}%' if d else '—'


def render():
    states = []
    for p in sorted(DIR.glob('*.json')):
        snap = json.loads(p.read_text())
        if 'by_category' in snap: states.append(snap)
    L = ['# Pipeline coverage dashboard', '',
         'Generated by `python -m pipeline dashboard` from `docs/coverage/pipeline/<STATE>.json`. '
         '"Found" = an official page for the category was fetched; "structured" = a record or candidate was extracted; '
         '"verified" = a verified record for the current year (newest available year for admissions/CDS) is in the repository.', '']
    for s in states:
        n = s['institutions']
        blocked = len(s.get('blocked_institutions', []))
        q = s.get('quality', {})
        L += [f"## {s['state']} — {s['academic_year']}", '',
              f"Institutions in scope: **{n}** · crawled: **{n - blocked}** · blocked by site: **{blocked}** · run: `{s.get('run', '')}`", '',
              '| category | verified | partially verified | structured (any) | source found (any) | not found | blocked |',
              '|---|---|---|---|---|---|---|']
        for cat in CATEGORIES:
            c = s['by_category'].get(cat, {})
            v = sum(c.get(k, 0) for k in VERIFIED)
            pv = c.get('partially_verified_current', 0)
            st = sum(c.get(k, 0) for k in STRUCTURED)
            fd = sum(c.get(k, 0) for k in FOUND)
            L.append(f"| {cat} | {v} ({pct(v, n)}) | {pv} | {st} ({pct(st, n)}) | {fd} ({pct(fd, n)}) | {c.get('not_found', 0)} | {c.get('fetch_failed', 0)} |")
        if q:
            L += ['', '| quality | count |', '|---|---|'] + [f'| {k.replace("_", " ")} | {v} |' for k, v in q.items()]
        if s.get('blocked_institutions'):
            L += ['', 'Browser/manual exception queue (sites refuse automated requests): ' + ', '.join(f'`{k}`' for k in s['blocked_institutions'])]
        L.append('')
    out = DIR / 'README.md'
    out.write_text('\n'.join(L) + '\n', encoding='utf-8')
    return out
