// Writes SQL that loads the app's original demo question fixtures into a disposable local database, so the real
// backend RPCs (sessions, benchmarks, grading, estimates) can be exercised end to end without the hosted project.
//
//   npx vite-node scripts/local/seedFromFixtures.ts > /tmp/seed.sql
//
// Local use only. The fixtures are original items written for this app (see fixtures.ts); this never touches a
// hosted database.
import { createHash } from 'node:crypto'
import { QUESTIONS, SKILLS, STRATEGIES, TRAPS } from '../../src/lib/data/demo/fixtures'

const q = (s: string | null | undefined) => (s == null ? 'null' : `'${s.replace(/'/g, "''")}'`)
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`
/** Stable uuid from a name, so reseeding gives the same ids. */
const uid = (name: string) => {
  const h = createHash('sha1').update(`collegeprep-local:${name}`).digest('hex')
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`
}

const VERSIONS = {
  act: { key: 'act_enhanced_2025', name: 'Enhanced ACT', from: '2025-04-01', rules: { scale: { min: 1, max: 36 }, science_optional: true } },
  sat: { key: 'sat_digital_2024', name: 'Digital SAT', from: '2024-03-01', rules: { scale: { min: 400, max: 1600 } } },
} as const

const out: string[] = ['-- Generated by web/scripts/local/seedFromFixtures.ts. Local disposable databases only.', 'begin;']
out.push(`insert into public.exam_families(key, name) values ('act','ACT'), ('sat','SAT') on conflict do nothing;`)
for (const [fam, v] of Object.entries(VERSIONS)) {
  out.push(
    `insert into public.exam_versions(id, exam_family, version_key, name, effective_from, rules) values (${q(uid(`ev:${fam}`))}, ${q(fam)}, ${q(v.key)}, ${q(v.name)}, ${q(v.from)}, ${j(v.rules)}) on conflict do nothing;`,
  )
  for (const t of ['choice', 'numeric'])
    out.push(
      `insert into public.question_types(id, exam_version_id, type_key, name) values (${q(uid(`qt:${fam}:${t}`))}, ${q(uid(`ev:${fam}`))}, ${q(t === 'choice' ? 'multiple_choice' : 'student_produced_response')}, ${q(t === 'choice' ? 'Multiple choice' : 'Student-produced response')}) on conflict do nothing;`,
    )
}
for (const s of SKILLS)
  out.push(
    `insert into public.skills(id, exam_family, section, domain, skill_key, name, concept_summary) values (${q(uid(`sk:${s.skill_key}`))}, ${q(s.exam_family)}, ${q(s.section)}, ${q(s.domain)}, ${q(s.skill_key)}, ${q(s.name)}, ${q(s.concept_summary ?? null)}) on conflict do nothing;`,
  )
for (const s of STRATEGIES)
  out.push(
    `insert into public.question_strategies(id, strategy_key, name, description, sections) values (${q(uid(`st:${s.strategy_key}`))}, ${q(s.strategy_key)}, ${q(s.name)}, ${q(s.description)}, array[${(s.sections ?? []).map(q).join(',')}]::text[]) on conflict do nothing;`,
  )
for (const t of TRAPS)
  out.push(`insert into public.trap_types(id, trap_key, name, description) values (${q(uid(`tr:${t.trap_key}`))}, ${q(t.trap_key)}, ${q(t.name)}, ${q(t.description)}) on conflict do nothing;`)

const label = (d: number) => (d <= 2 ? 'easy' : d === 3 ? 'medium' : 'hard')
for (const x of QUESTIONS) {
  const id = uid(`q:${x.id}`)
  const ev = uid(`ev:${x.exam_family}`)
  let passage = 'null'
  if (x.passage) {
    passage = q(uid(`p:${x.id}`))
    out.push(`insert into public.practice_passages(id, exam_version_id, body) values (${passage}, ${q(ev)}, ${q(x.passage)}) on conflict do nothing;`)
  }
  // The backend grades numeric answers by value, so only plain numbers/fractions are stored (it rejects "$63").
  const accepted = x.answer_format === 'numeric' ? x.accepted_answers.filter((a) => /^-?([0-9]+\.?[0-9]*|\.[0-9]+|[0-9]+\/[0-9]+)$/.test(a.replace(/\s/g, ''))) : x.accepted_answers
  const remember = x.remember && x.remember.trim().split(/\s+/).length <= 16 ? x.remember : null
  out.push(
    `insert into public.practice_questions(id, exam_version_id, question_type_id, section, difficulty, difficulty_label, stem, choices, answer_format, accepted_answers, hints, teaching_explanation, strategy_explanation, expected_time_seconds, status, passage_id, remember_text, source_attribution) values (${q(id)}, ${q(ev)}, ${q(uid(`qt:${x.exam_family}:${x.answer_format}`))}, ${q(x.section)}, ${x.difficulty}, ${q(label(x.difficulty))}, ${q(x.stem)}, ${j(x.choices)}, ${q(x.answer_format)}, ${j(accepted)}, ${j(x.hints)}, ${q(x.teaching_explanation)}, ${q(x.strategy_explanation)}, ${x.expected_time_seconds}, 'published', ${passage}, ${q(remember)}, 'Prep & Price original demo item') on conflict do nothing;`,
  )
  out.push(`insert into public.practice_question_skills(question_id, skill_id, is_primary) values (${q(id)}, ${q(uid(`sk:${x.primary_skill_key}`))}, true) on conflict do nothing;`)
  for (const d of x.distractors)
    out.push(
      `insert into public.practice_question_distractors(question_id, choice_key, rationale, trap_type_id) values (${q(id)}, ${q(d.choice)}, ${q(d.rationale)}, ${d.trap ? q(uid(`tr:${d.trap}`)) : 'null'}) on conflict do nothing;`,
    )
  for (const s of x.strategies)
    out.push(
      `insert into public.practice_question_strategies(question_id, strategy_id, role, is_fastest, strategy_explanation) values (${q(id)}, ${q(uid(`st:${s.strategy_key}`))}, ${q(s.role)}, ${s.is_fastest}, ${q(s.explanation)}) on conflict do nothing;`,
    )
}
out.push('commit;')
process.stdout.write(out.join('\n') + '\n')
