#!/usr/bin/env python3
"""Reconcile the national registry against the IPEDS four-year institution universe (docs/coverage/registry_reconciliation.*).

Universe: IPEDS HD2023 (2023-24 collection, the pinned file in sources/ipeds/2023-24), institutions with ICLEVEL = 1
(highest offering four years or above), CYACTIVE = 1, DEGGRANT = 1 and PSET4FLG = 1 (Title IV), in the 50 states and
D.C. That is the NCES Digest's "degree-granting 4-year institutions" population. Every one is either in the registry or
listed with the reason it is not. `--check` fails when the committed report is stale.
"""
from __future__ import annotations
import collections, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from pipeline.registry import hd_rows  # noqa: E402

STATES = set('AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK '
             'OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split())
CONTROL = {'1': 'public', '2': 'private_nonprofit', '3': 'private_for_profit'}
REASONS = {
    'for_profit': 'Private for-profit (IPEDS CONTROL 3): outside the product scope (public and private nonprofit).',
    'graduate_only': 'Offers no undergraduate instruction (UGOFFER not 1): graduate and professional schools.',
    'administrative_unit': 'System, district or board office (IPEDS INSTCAT -2): reports to IPEDS but enrolls no students.',
    'graduate_degrees_only': 'IPEDS INSTCAT 1: degree-granting, graduate degrees only (undergraduate courses without an undergraduate degree).',
    'category_not_reported': 'IPEDS INSTCAT -1 (not reported): held for a manual check of whether undergraduate degrees are awarded.',
    'other': 'Excluded by the registry scope rule for another reason; see the row.',
}


def reason(r):
    if r['CONTROL'] == '3': return 'for_profit'
    if r['UGOFFER'] != '1': return 'graduate_only'
    if r.get('INSTCAT') == '-2': return 'administrative_unit'
    if r.get('INSTCAT') == '1': return 'graduate_degrees_only'
    if r.get('INSTCAT') == '-1': return 'category_not_reported'
    return 'other'


def build():
    registry = {}
    for p in sorted((ROOT / 'pipeline/registry').glob('*.json')):
        if len(p.stem) == 2 and p.stem in STATES:
            for i in json.loads(p.read_text())['institutions']:
                registry[str(i['unitid'])] = (p.stem, i['level'])
    hd = hd_rows()
    universe = [r for r in hd if r['STABBR'] in STATES and r['ICLEVEL'] == '1' and r['CYACTIVE'] == '1'
                and r['DEGGRANT'] == '1' and r['PSET4FLG'] == '1']
    territories = sum(1 for r in hd if r['STABBR'] not in STATES and r['ICLEVEL'] == '1' and r['CYACTIVE'] == '1'
                      and r['DEGGRANT'] == '1' and r['PSET4FLG'] == '1')
    reg4 = {u for u, (s, lv) in registry.items() if lv == 'four_year'}
    in_universe = {r['UNITID'] for r in universe}
    excluded = [r for r in universe if r['UNITID'] not in reg4]
    by_reason = collections.Counter(reason(r) for r in excluded)
    by_state = collections.defaultdict(lambda: collections.Counter())
    for r in universe:
        by_state[r['STABBR']]['universe'] += 1
        by_state[r['STABBR']]['registered' if r['UNITID'] in reg4 else 'excluded'] += 1
    return {
        'source': 'IPEDS HD2023 (2023-24 collection), sources/ipeds/2023-24/manifest.json',
        'universe_definition': 'ICLEVEL 1 (four-year or above), CYACTIVE 1 (active), DEGGRANT 1 (degree-granting), PSET4FLG 1 '
                               '(Title IV), 50 states and D.C.: the NCES Digest population of degree-granting 4-year institutions',
        'registry_scope_rule': 'pipeline/registry.py in_scope',
        'national_four_year_universe': len(universe),
        'universe_by_control': dict(collections.Counter(CONTROL[r['CONTROL']] for r in universe)),
        'territories_and_other_jurisdictions_not_counted': territories,
        'registered_four_year': len(reg4),
        'registered_in_universe': len(reg4 & in_universe),
        'registered_outside_universe': sorted(reg4 - in_universe),
        'outside_universe_note': 'Registered four-year schools that are not Title IV participants (PSET4FLG not 1); the registry '
                                 'scope does not require Title IV.',
        'excluded_from_universe': len(excluded),
        'excluded_by_reason': dict(sorted(by_reason.items())),
        'reasons': REASONS,
        'by_state': {s: dict(c) for s, c in sorted(by_state.items())},
        'excluded': sorted(({'unitid': int(r['UNITID']), 'name': r['INSTNM'], 'state': r['STABBR'], 'control': CONTROL[r['CONTROL']],
                             'reason': reason(r)} for r in excluded), key=lambda x: (x['reason'], x['state'], x['name'])),
    }


def markdown(d):
    L = ['# Registry reconciliation against the IPEDS four-year universe', '',
         f"Generated by `python scripts/registry_reconciliation.py` from {d['source']}.", '',
         f"- **National four-year universe: {d['national_four_year_universe']}** ({d['universe_definition']}). "
         f"By control: {', '.join(f'{k} {v}' for k, v in sorted(d['universe_by_control'].items()))}. "
         f"Territories and freely associated states are not counted ({d['territories_and_other_jurisdictions_not_counted']}).",
         f"- **Registered four-year schools: {d['registered_four_year']}** across 50 states and D.C. "
         f"({d['registered_in_universe']} in the universe, {len(d['registered_outside_universe'])} not Title IV participants).",
         f"- **Not registered: {d['excluded_from_universe']}**, each with a documented reason:", '']
    L += [f"  - {k}: {v} — {d['reasons'][k]}" for k, v in d['excluded_by_reason'].items()]
    L += ['', 'Deep-dive progress is reported separately (registered, researched, covered) in `docs/coverage/programs/STATUS.md`.', '',
          '| State | Universe | Registered | Not registered |', '|---|---|---|---|']
    L += [f"| {s} | {c.get('universe', 0)} | {c.get('registered', 0)} | {c.get('excluded', 0)} |" for s, c in d['by_state'].items()]
    L += ['', '## Not registered', '', '| Reason | State | Institution | UNITID | Control |', '|---|---|---|---|---|']
    L += [f"| {x['reason']} | {x['state']} | {x['name']} | {x['unitid']} | {x['control']} |" for x in d['excluded']]
    return '\n'.join(L) + '\n'


def main(check=False):
    d = build(); j = json.dumps(d, indent=1, sort_keys=True) + '\n'
    out = ROOT / 'docs/coverage'
    if check:
        cur = (out / 'registry_reconciliation.json').read_text() if (out / 'registry_reconciliation.json').exists() else ''
        if cur != j: print('docs/coverage/registry_reconciliation.json is stale: run python scripts/registry_reconciliation.py'); return 1
        print(f"Registry reconciliation current: {d['registered_four_year']} registered of {d['national_four_year_universe']}"); return 0
    (out / 'registry_reconciliation.json').write_text(j); (out / 'registry_reconciliation.md').write_text(markdown(d))
    print({k: d[k] for k in ('national_four_year_universe', 'registered_four_year', 'registered_in_universe', 'excluded_from_universe', 'excluded_by_reason')})
    return 0


if __name__ == '__main__':
    raise SystemExit(main(check='--check' in sys.argv))
